"""Публичный API конфигурации `thermal_tracker`."""

from .app_config import (
    AppConfig,
    CommandConnectionConfig,
    ConnectionsConfig,
    FrameConnectionConfig,
    GuiConfig,
    HistoryConfig,
    ModelConfig,
    ResultConnectionConfig,
    RuntimeConfig,
    TrackerRunConfig,
    load_app_config,
)
from .preset import (
    AVAILABLE_PRESETS,
    ClickSelectionConfig,
    DEFAULT_PRESET_NAME,
    GlobalMotionConfig,
    IrstTrackerConfig,
    NeuralConfig,
    OpenCVTrackerConfig,
    PROJECT_ROOT,
    PresetPresentation,
    PreprocessingConfig,
    TrackerPreset,
    VisualizationConfig,
    YoloTrackerConfig,
    build_preset,
    get_available_preset_names,
    get_preset_presentation,
)

__all__ = [
    "AVAILABLE_PRESETS",
    "AppConfig",
    "ClickSelectionConfig",
    "CommandConnectionConfig",
    "ConnectionsConfig",
    "DEFAULT_PRESET_NAME",
    "FrameConnectionConfig",
    "GlobalMotionConfig",
    "GuiConfig",
    "HistoryConfig",
    "IrstTrackerConfig",
    "ModelConfig",
    "NeuralConfig",
    "OpenCVTrackerConfig",
    "PROJECT_ROOT",
    "PresetPresentation",
    "PreprocessingConfig",
    "ResultConnectionConfig",
    "RuntimeConfig",
    "TrackerPreset",
    "TrackerRunConfig",
    "VisualizationConfig",
    "YoloTrackerConfig",
    "build_preset",
    "get_available_preset_names",
    "get_preset_presentation",
    "load_app_config",
]
